In [6]:
import numpy  as np

In [7]:
x = [1,2,3,4,5]
z = np.array([[x,x,x],[x,x,x],[x,x,x]])
print('shape',z.shape)
print(z)

shape (3, 3, 5)
[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


In [8]:
np.arange(0,10,.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [11]:
d = np.arange(-10,11,.5)
d.shape

(42,)

In [12]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [13]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [14]:
a = np.linspace(1, 1000, 10)
a

array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
       1000.])

In [16]:
d = np.random.randint(1,6,(10,10))

In [17]:
print(d)

[[2 4 4 3 1 1 5 1 2 4]
 [5 1 3 5 1 5 5 5 3 4]
 [2 1 4 1 1 1 2 2 5 4]
 [2 1 1 1 2 4 1 4 3 5]
 [1 5 4 3 2 5 3 4 1 1]
 [5 4 2 5 5 3 1 5 3 3]
 [4 5 3 4 4 5 1 5 4 2]
 [4 5 2 2 5 5 5 1 5 4]
 [5 4 4 5 5 3 4 5 1 2]
 [1 1 2 4 5 3 3 5 3 1]]


In [18]:
d[0]

array([2, 4, 4, 3, 1, 1, 5, 1, 2, 4])

In [19]:
d[-1]

array([1, 1, 2, 4, 5, 3, 3, 5, 3, 1])

In [20]:
d[0,0]

2

In [21]:
d[4][4]

2

In [22]:
d[5][4]

5

In [23]:
d[:, 0] #all rows of column index 0

array([2, 5, 2, 2, 1, 5, 4, 4, 5, 1])

In [24]:
d[:5, 2]

array([4, 3, 4, 1, 4])

In [25]:
d[:5, 4]

array([1, 1, 1, 2, 2])

In [26]:
d[5, -1]

3

In [27]:
d[:5, -1]

array([4, 4, 4, 5, 1])

In [28]:
d[:5, :5] 

array([[2, 4, 4, 3, 1],
       [5, 1, 3, 5, 1],
       [2, 1, 4, 1, 1],
       [2, 1, 1, 1, 2],
       [1, 5, 4, 3, 2]])

In [29]:
x = np.random.randint(1, 10, (3,3))
y = np.random.randint(1,10,(3,3))
print(x,'\n',y)

[[2 3 3]
 [7 7 4]
 [2 7 3]] 
 [[8 5 4]
 [6 5 3]
 [2 4 6]]


In [30]:
x+y

array([[10,  8,  7],
       [13, 12,  7],
       [ 4, 11,  9]])

In [31]:
x-y

array([[-6, -2, -1],
       [ 1,  2,  1],
       [ 0,  3, -3]])

In [32]:
x*y

array([[16, 15, 12],
       [42, 35, 12],
       [ 4, 28, 18]])

In [33]:
x/y

array([[0.25      , 0.6       , 0.75      ],
       [1.16666667, 1.4       , 1.33333333],
       [1.        , 1.75      , 0.5       ]])

In [34]:
x + 20

array([[22, 23, 23],
       [27, 27, 24],
       [22, 27, 23]])

In [35]:
x - 10

array([[-8, -7, -7],
       [-3, -3, -6],
       [-8, -3, -7]])

In [36]:
np.dot(x,y)

array([[ 40,  37,  35],
       [106,  86,  73],
       [ 64,  57,  47]])

In [37]:
np.matmul(x,y) #matrix multiplication

array([[ 40,  37,  35],
       [106,  86,  73],
       [ 64,  57,  47]])

In [38]:
np.cross(x,y)

array([[ -3,  16, -14],
       [  1,   3,  -7],
       [ 30,  -6,  -6]])

In [39]:
np.hstack([x,y])

array([[2, 3, 3, 8, 5, 4],
       [7, 7, 4, 6, 5, 3],
       [2, 7, 3, 2, 4, 6]])

In [40]:
np.vstack([x,y])

array([[2, 3, 3],
       [7, 7, 4],
       [2, 7, 3],
       [8, 5, 4],
       [6, 5, 3],
       [2, 4, 6]])

In [42]:
np.append(x,[1,2,3])

array([2, 3, 3, 7, 7, 4, 2, 7, 3, 1, 2, 3])

In [43]:
np.append(x,y,axis=0)

array([[2, 3, 3],
       [7, 7, 4],
       [2, 7, 3],
       [8, 5, 4],
       [6, 5, 3],
       [2, 4, 6]])

In [44]:
x.max()

7

In [45]:
x.max(axis=0)

array([7, 7, 4])

In [46]:
x.min(axis=1)

array([2, 4, 2])

In [47]:
x.flatten()

array([2, 3, 3, 7, 7, 4, 2, 7, 3])

In [48]:
d

array([[2, 4, 4, 3, 1, 1, 5, 1, 2, 4],
       [5, 1, 3, 5, 1, 5, 5, 5, 3, 4],
       [2, 1, 4, 1, 1, 1, 2, 2, 5, 4],
       [2, 1, 1, 1, 2, 4, 1, 4, 3, 5],
       [1, 5, 4, 3, 2, 5, 3, 4, 1, 1],
       [5, 4, 2, 5, 5, 3, 1, 5, 3, 3],
       [4, 5, 3, 4, 4, 5, 1, 5, 4, 2],
       [4, 5, 2, 2, 5, 5, 5, 1, 5, 4],
       [5, 4, 4, 5, 5, 3, 4, 5, 1, 2],
       [1, 1, 2, 4, 5, 3, 3, 5, 3, 1]])

In [49]:
d[d>3]  #boolean filter

array([4, 4, 5, 4, 5, 5, 5, 5, 5, 4, 4, 5, 4, 4, 4, 5, 5, 4, 5, 4, 5, 4,
       5, 5, 5, 4, 5, 4, 4, 5, 5, 4, 4, 5, 5, 5, 5, 5, 4, 5, 4, 4, 5, 5,
       4, 5, 4, 5, 5])

In [50]:
d[d==1] # give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])